// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 关于我们 (about)
// Source: 素材/关于我们 照片/
// Slots: intro, affiliation, philosophy, labAi, labCulture
export const aboutPhotoSrc = {
  "intro": "/assets/page-photos/about/01.jpg",
  "affiliation": "/assets/page-photos/about/02.jpg",
  "philosophy": "/assets/page-photos/about/03.jpg",
  "labAi": "/assets/page-photos/about/04.jpg",
  "labCulture": "/assets/page-photos/about/05.jpg"
} as const;

export type AboutPhotoSlot = keyof typeof aboutPhotoSrc;
