// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 荣誉成果 (achievements)
// Source: 素材/荣誉成果 照片/
export interface AchievementsGalleryItem {
  src: string;
  caption: string;
}

export const achievementsGallery: AchievementsGalleryItem[] = [];
