// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 荣誉成果 (achievements)
// Source: 素材/荣誉成果 照片/
export interface AchievementsGalleryItem {
  src: string;
  caption: string;
}

export const achievementsGallery: AchievementsGalleryItem[] = [
  {
    "src": "/assets/page-photos/achievements/01-全国青少年科技社团支持计划.png",
    "caption": "01-全国青少年科技社团支持计划"
  },
  {
    "src": "/assets/page-photos/achievements/02-兰州大学十佳学生社团指导教师.png",
    "caption": "02-兰州大学十佳学生社团指导教师"
  },
  {
    "src": "/assets/page-photos/achievements/03-青年夜校示范项目.png",
    "caption": "03-青年夜校示范项目"
  },
  {
    "src": "/assets/page-photos/achievements/04-社团文化节心动运营社团奖.png",
    "caption": "04-社团文化节心动运营社团奖"
  },
  {
    "src": "/assets/page-photos/achievements/05-教育信息技术应用创新大赛西北赛区一等奖.png",
    "caption": "05-教育信息技术应用创新大赛西北赛区一等奖"
  },
  {
    "src": "/assets/page-photos/achievements/06-官方媒体深度报道.png",
    "caption": "06-官方媒体深度报道"
  },
  {
    "src": "/assets/page-photos/achievements/07-2026技嘉X英伟达 桌面AI超算竞赛 最具开发潜力奖.png",
    "caption": "07-2026技嘉X英伟达 桌面AI超算竞赛 最具开发潜力奖"
  },
  {
    "src": "/assets/page-photos/achievements/08-2026 启元人工智能大赛 九齿SKILL开发赛道 全国第1名.png",
    "caption": "08-2026 启元人工智能大赛 九齿SKILL开发赛道 全国第1名"
  },
  {
    "src": "/assets/page-photos/achievements/09-2026 第二届百度秒哒杯人工智能通识应用大赛 最具潜力奖.png",
    "caption": "09-2026 第二届百度秒哒杯人工智能通识应用大赛 最具潜力奖"
  }
];
