// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 品牌活动 (activities)
// Source: 素材/品牌活动 照片/
export interface ActivitiesGalleryItem {
  src: string;
  caption: string;
}

export const activitiesGallery: ActivitiesGalleryItem[] = [];
