// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 首页 · 社团概况 / 发展历程 (home-overview)
// Source: 素材/首页 社团概况 照片/
export interface HomeOverviewGalleryItem {
  src: string;
  caption: string;
}

export const homeOverviewGallery: HomeOverviewGalleryItem[] = [
  {
    "src": "/assets/page-photos/home-overview/01 社团管理人员召开工作会议.jpg",
    "caption": "01 社团管理人员召开工作会议"
  },
  {
    "src": "/assets/page-photos/home-overview/02.jpg",
    "caption": "02"
  },
  {
    "src": "/assets/page-photos/home-overview/03.jpg",
    "caption": "03"
  },
  {
    "src": "/assets/page-photos/home-overview/04.jpg",
    "caption": "04"
  },
  {
    "src": "/assets/page-photos/home-overview/05.jpg",
    "caption": "05"
  },
  {
    "src": "/assets/page-photos/home-overview/06.jpg",
    "caption": "06"
  },
  {
    "src": "/assets/page-photos/home-overview/07.jpg",
    "caption": "07"
  },
  {
    "src": "/assets/page-photos/home-overview/08.jpeg",
    "caption": "08"
  },
  {
    "src": "/assets/page-photos/home-overview/09.jpg",
    "caption": "09"
  },
  {
    "src": "/assets/page-photos/home-overview/10.jpg",
    "caption": "10"
  }
];
