// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 加入我们 (join)
// Source: 素材/加入我们 照片/
export interface JoinGalleryItem {
  src: string;
  caption: string;
}

export const joinGallery: JoinGalleryItem[] = [
  {
    "src": "/assets/page-photos/join/qq-group-qr.png",
    "caption": "qq-group-qr"
  }
];
