// Auto-generated by scripts/sync-news-photos.mjs — do not edit manually
// Source: 素材/新闻动态 照片/
// Match news items by date field in src/content/news.ts

export interface NewsMediaEntry {
  date: string;
  cover: string;
  images: string[];
}

export const newsMediaByDate: Record<string, NewsMediaEntry> = {
  "2026-03-05": {
    "date": "2026-03-05",
    "cover": "/assets/news/2026-03-05.jpg",
    "images": [
      "/assets/news/2026-03-05.jpg"
    ]
  },
  "2026-03-07": {
    "date": "2026-03-07",
    "cover": "/assets/news/2026-03-07.jpg",
    "images": [
      "/assets/news/2026-03-07.jpg"
    ]
  },
  "2026-03-18": {
    "date": "2026-03-18",
    "cover": "/assets/news/2026-03-18.jpg",
    "images": [
      "/assets/news/2026-03-18.jpg"
    ]
  },
  "2026-03-21": {
    "date": "2026-03-21",
    "cover": "/assets/news/2026-03-21.jpg",
    "images": [
      "/assets/news/2026-03-21.jpg"
    ]
  },
  "2026-04-03": {
    "date": "2026-04-03",
    "cover": "/assets/news/2026-04-03.jpg",
    "images": [
      "/assets/news/2026-04-03.jpg"
    ]
  },
  "2026-04-17": {
    "date": "2026-04-17",
    "cover": "/assets/news/2026-04-17.jpg",
    "images": [
      "/assets/news/2026-04-17.jpg"
    ]
  },
  "2026-05-06": {
    "date": "2026-05-06",
    "cover": "/assets/news/2026-05-06.jpg",
    "images": [
      "/assets/news/2026-05-06.jpg"
    ]
  },
  "2026-05-11": {
    "date": "2026-05-11",
    "cover": "/assets/news/2026-05-11.jpg",
    "images": [
      "/assets/news/2026-05-11.jpg"
    ]
  },
  "2026-05-18": {
    "date": "2026-05-18",
    "cover": "/assets/news/2026-05-18.jpg",
    "images": [
      "/assets/news/2026-05-18.jpg"
    ]
  },
  "2026-06-17": {
    "date": "2026-06-17",
    "cover": "/assets/news/2026-06-17.jpg",
    "images": [
      "/assets/news/2026-06-17.jpg"
    ]
  },
  "2026-06-19": {
    "date": "2026-06-19",
    "cover": "/assets/news/2026-06-19.jpg",
    "images": [
      "/assets/news/2026-06-19.jpg"
    ]
  }
};
