// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 组织架构 · 历届档案封面 (organization)
// Source: 素材/组织架构 照片/
// Slots: gen-1
export const organizationCohortCovers = {
  "gen-1": "/assets/page-photos/organization/01.jpg"
} as const;

export type OrganizationCohortCovers = keyof typeof organizationCohortCovers;
