// Auto-generated by scripts/sync-page-photos.mjs — do not edit manually
// Page: 科研方向 (projects)
// Source: 素材/科研方向 照片/
export interface ProjectsGalleryItem {
  src: string;
  caption: string;
}

export const projectsGallery: ProjectsGalleryItem[] = [];
